server {
    listen 80;
    server_name 35.229.197.41.nip.io;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name 35.229.197.41.nip.io;
    client_max_body_size 50M;

    ssl_certificate /etc/letsencrypt/live/35.229.197.41.nip.io/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/35.229.197.41.nip.io/privkey.pem;

    location / {
        proxy_pass http://localhost:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_cache_bypass $http_upgrade;
    }
}
